### ISSUE TITLE
Use separate pages for Applications?

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS-website#10]
Up for discussion. I think it currently looks a bit messy.
Of course it all can stay under the Applications page. Even the sidebar can/should stay.

**Comment by rahul799** [comment]
Hi @jpfeuffer. Last time we agreed with "keeping the Applications page inside Use Cases menu bar". @timosachsenberg what do you think?

**Comment by jpfeuffer** [comment]
I don't care about this. As long as all the applications are not just pasted under each other and become completely unreasonable

**Comment by timosachsenberg** [comment]
I agree with Julianus. It looked cleaner on the old page

**Comment by rahul799** [comment]
Hi @jpfeuffer,
Now I have added a read more button at the end of each section wherever the content was exceeding a page. 
Can you please review once?

**Comment by timosachsenberg** [comment]
- some buttons can't be clicked ("check it out on github")
- buttons"Download example TOPPAS workflows" has no mouse indicator that it can be clicked
- how to get easily back to the overview page?
- navigation a bit of confusing because e.g., https://openms.github.io/application/flashdeconv/ has its own sidebar while others don't

**Comment by rahul799** [comment]
Hi @timosachsenberg ,
Thank you for the review.
Actually flashdeconv has lots of content and hence I added the sidebar. But yes, I think sidebar must be there in other pages too. So I will add them.

**Comment by timosachsenberg** [comment]
Is this easy to grasp for the user "where" he is in the link hierarchy?

**Comment by rahul799** [comment]
Hi Timo,
For long pages, it makes easy for the user to view all the headings in the sidebar.

> * some buttons can't be clicked ("check it out on github")
> * buttons"Download example TOPPAS workflows" has no mouse indicator that it can be clicked

Fixed. Also I have added snippet support for the buttons,
Ex: 
```
{{< button normal link >}}
Normal Button
{{< /button >}}

{{< button download link >}}
Download Button
{{< /button >}}

```
I will add more about it in theme's documentation 

> * how to get easily back to the overview page?
> * navigation a bit of confusing because e.g., https://openms.github.io/application/flashdeconv/ has its own sidebar while others don't

So I have attached the sidebars in most of the pages except [some](http://localhost:1313/application/diaproteomics/) where no heading was there.

**Comment by enetz** [comment]
the main application page does look a bit chaotic and heterogeneous. 

- FlashDeconv is split up into two. I think it should be one section, with a notice on the bottom of its own page about the new version or something.
- the link to the "FlashDeconv repo" is just a forked whole OpenMS repo, without specific instructions or info about the application
- the GitHub buttons are honestly annoying. It doesn't show the link destination with mouseover, which is already weird and sketchy security-wise. And you can't right click to open in a new tab.

some of the chaos was brought over from the old website, but it didn't look this disorganized on separate pages, since you never see the different "styles" of the pages at the same time over there
